# Linux makefile for FreeImage

# This file can be generated by ./gensrclist.sh
include Makefile.srcs

TARGET  = freeimage
HEADER = Source/FreeImage.h
HEADERS_INSTALL = $(HEADER)

include Makefile.common
